fix backend workflow

diff --git a/.github/workflows/feature-portfolio-content_muhammad-portfolio-backend.yml b/.github/workflows/feature-portfolio-content_muhammad-portfolio-backend.yml
--- a/.github/workflows/feature-portfolio-content_muhammad-portfolio-backend.yml
+++ b/.github/workflows/feature-portfolio-content_muhammad-portfolio-backend.yml
@@ -30,7 +30,10 @@ jobs:
           source venv/bin/activate
       
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: |
+          cd backend
+          python -m pip install --upgrade pip
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1;
         
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
